"""empty message

Revision ID: 11765ba15489
Revises: 
Create Date: 2019-06-04 21:54:41.904140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11765ba15489'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('usernamed', sa.String(length=20), nullable=False))
    op.create_unique_constraint(None, 'user', ['usernamed'])
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=20), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'usernamed')
    # ### end Alembic commands ###
